apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linuxptp-daemon
  namespace: openshift-ptp
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linuxptp-daemon
  namespace: openshift-ptp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linuxptp-daemon
subjects:
- kind: ServiceAccount
  name: linuxptp-daemon
  namespace: openshift-ptp