package constants

const (
	// Master ...
	Master = "master"
	// Interface ...
	Interface = "interface"

	// Phc ...
	Phc = "phc"
	// Sys ...
	Sys = "sys"
	// ClockRealTime ...
	ClockRealTime = "CLOCK_REALTIME"
	// NmeaStatus ...
	NmeaStatus = "nmea_status"

	// Parsing field constants

	// Timestamp ...
	Timestamp = "timestamp"
	// ConfigName ...
	ConfigName = "config_name"
	// Severity ...
	Severity = "severity"
	// ServoState ...
	ServoState = "servo_state"
	// Offset ...
	Offset = "offset"
)
