package constants

// PTPPortRole ...
type PTPPortRole int

const (
	// PortRolePassive ...
	PortRolePassive PTPPortRole = iota
	// PortRoleSlave ...
	PortRoleSlave
	// PortRoleMaster ...
	PortRoleMaster
	// PortRoleFaulty ...
	PortRoleFaulty
	// PortRoleUnknown ...
	PortRoleUnknown
	// PortRoleListening ...
	PortRoleListening
)
